{{- if .Values.opencloud.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencloud.opencloud.fullname" . }}-config
  labels:
    {{- include "opencloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: opencloud
data:
  # App registry configuration
  app-registry.yaml: |-
{{- if empty .Values.opencloud.config.appRegistry -}}
{{ .Files.Get "files/opencloud/app-registry.yaml" | nindent 4 }}
{{- else -}}
{{ toYaml (dict "app_registry" .Values.opencloud.config.appRegistry) | nindent 4 }}
{{- end }}

  # CSP configuration
  csp.yaml: |-
{{- if empty .Values.opencloud.config.csp -}}
{{ tpl (.Files.Get "files/opencloud/csp.yaml.gotmpl") . | nindent 4 }}
{{- else -}}
{{ .Values.opencloud.config.csp | nindent 4 }}
{{- end }}

  # Custom patch
  proxy.yaml: |-
    role_assignment:
      driver: oidc
      oidc_role_mapper:
          role_claim: groups
          role_mapping:
              - role_name: admin    # Opencloud role name
                claim_value: admins # Authentik group name
              - role_name: user
                claim_value: authentik users
              - role_name: guest
                claim_value: authentik users
    additional_policies:
      - name: default
        routes:
          - endpoint: /caldav/
            backend: http://radicale:5232
            remote_user_header: X-Remote-User
            skip_x_access_token: true
            additional_headers:
              - X-Script-Name: /caldav
          - endpoint: /.well-known/caldav
            backend: http://radicale:5232
            remote_user_header: X-Remote-User
            skip_x_access_token: true
            additional_headers:
              - X-Script-Name: /caldav
          - endpoint: /carddav/
            backend: http://radicale:5232
            remote_user_header: X-Remote-User
            skip_x_access_token: true
            additional_headers:
              - X-Script-Name: /carddav
          - endpoint: /.well-known/carddav
            backend: http://radicale:5232
            remote_user_header: X-Remote-User
            skip_x_access_token: true
            additional_headers:
              - X-Script-Name: /carddav

  # Banned password list
  banned-password-list.txt: |-
{{- if empty .Values.opencloud.config.bannedPasswordList -}}
{{- .Files.Get "files/opencloud/banned-password-list.txt" | nindent 4 }}
{{- else -}}
{{- .Values.opencloud.config.bannedPasswordList | nindent 4 }}
{{- end }}

  # Search configuration
  search.yaml: |-
{{- .Files.Get "files/opencloud/search.yaml" | nindent 4 }}

{{- end }}
